services:
  minecraft:
    build: .
    container_name: "${CONTAINER_NAME}"
    ports:
      - "${PORT}:25565"
    volumes:
      - ./data:/app
      - ./mods:/app/mods
    env_file:
      - .env
    environment:
      CONTAINER_NAME: "${CONTAINER_NAME}"
      SERVER_TYPE: "${SERVER_TYPE}"
      MC_VERSION: "${MC_VERSION}"
      FABRIC_INSTALLER_VERSION: "${FABRIC_INSTALLER_VERSION}"
      FORGE_INSTALLER_VERSION: "${FORGE_INSTALLER_VERSION}"
      QUILT_INSTALLER_VERSION: "${QUILT_INSTALLER_VERSION}"
      JVM_OPTS: "-Xmx${MEMORY_MAX} -Xms${MEMORY_MIN}"
      EULA: "${EULA}"
      WORLD_NAME: "${WORLD_NAME}"
      DIFFICULTY: "${DIFFICULTY}"
      GAMEMODE: "${GAMEMODE}"
      MAX_PLAYERS: "${MAX_PLAYERS}"
      VIEW_DISTANCE: "${VIEW_DISTANCE}"
      ENABLE_COMMAND_BLOCKS: "${ENABLE_COMMAND_BLOCKS}"
      ALLOW_FLIGHT: "${ALLOW_FLIGHT}"
      MOTD: "${MOTD}"
      ONLINE_MODE: "${ONLINE_MODE}"
      WHITE_LIST: "${WHITE_LIST}"
    stdin_open: true
    tty: true
    restart: unless-stopped
